name: Scrape and Send LinkedIn Jobs

on:
  schedule:
    - cron: '0 19 * * *'  # Runs at 7:00 PM UTC every day
  workflow_dispatch:  # Allow manual trigger from GitHub

jobs:
  run-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        env:
          TELEGRAM_URL: ${{ secrets.TELEGRAM_URL }}  # Store your Telegram URL in GitHub secrets
        run: |
          python linkedin.py
