name: Scrape LinkedIn Jobs and Send to Telegram

on:
  schedule:
    # Run the job every day at 6 AM Nigerian time (UTC+1)
    - cron: "0 5 * * *"  # 5 AM UTC corresponds to 6 AM Nigerian time (UTC+1)

  # Allow manual triggering for testing purposes
  workflow_dispatch:

jobs:
  scrape-and-send:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Specify the Python version you're using

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install undetected-chromedriver selenium pandas requests

      # Step 4: Run the Python script
      - name: Run scraper script
        env:
          TELEGRAM_URL: ${{ secrets.TELEGRAM_URL }}  # Access the secret from GitHub
        run: |
          python linkedin.py  
